### ISSUE TITLE
Values x4 larger when demosaic_first=True

### ISSUE THREAD

**Issue by mantiuk** [gfxdisp/HDRutils#2]
When I pass `demosaic_first=True` to `merge`, the resulting values in HDR images are 4x larger than when `demosaic_first=False`. I assume the values should be comparable.

**Comment by paramhanji** [comment]
Yes, this is to be expected. With `demosaic=False`, RAW images are processed by Libraw, which outputs 16 bit values. With the manual `demosaic=True`, pixel values are consistent with RAW camera readout. The 4x difference is because the camera you used probably has a 14-bit readout.

**Comment by mantiuk** [comment]
For the sake of colour calibration, it would be helpful if both modes returned the same values - perhaps replicate the LibRAW processing when `demosaic_first=False`?
