### ISSUE TITLE
Image examples

### ISSUE THREAD

**Issue by andriyrizhiy** [gfxdisp/HDRutils#5]
Hello! Can you provide examples of your input and output data that you showed in the paper as examples?

**Comment by paramhanji** [comment]
Hi,
Thanks for your suggestion. The images in our papers are quite large and may not be the most suitable for inclusion in this Github repository. May I suggest that you visit [this project](https://openexr.com/en/latest/_test_images/index.html) to download some sample images instead?

You can also find some images from our papers in the following datasets: [Fairchild survey](http://markfairchild.org/HDR.html) and [SI-HDR](https://www.repository.cam.ac.uk/items/c02ccdde-db20-4acd-8941-7816ef6b7dc7).
